version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network
  
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - dev-network

volumes:
  postgres-data:
    driver: local

networks:
  dev-network:
    driver: bridge
